plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
}

version = '1.2.5'
group = 'com.lightyorugami.reworkedphantoms'

base {
    archivesName = 'reworkedphantoms'
}

// Mojang ships Java 21 to end users in 1.20.5+, so your mod should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

minecraft {

    mappings channel: mapping_channel, version: mapping_version

    reobf = false

    copyIdeResources = true

    runs {

        configureEach {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
        }

        client {
            property 'forge.enabledGameTestNamespaces', 'reworkedphantoms'
        }

        server {
            property 'forge.enabledGameTestNamespaces', 'reworkedphantoms'
            args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', 'reworkedphantoms'
        }

        data {
            workingDirectory project.file('run-data')

            args '--mod', 'reworkedphantoms', '--all',
                    '--output', file('src/generated/resources/'),
                    '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
}

dependencies {

    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

}

tasks.named('processResources', ProcessResources).configure {

    var replaceProperties = [
            minecraft_version: minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version: forge_version,
            forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,

            mod_id: 'reworkedphantoms',
            mod_name: 'Reworked Phantoms',
            mod_license: 'GPLv3',
            mod_version: '1.2.4',
            mod_authors: 'lightyorugami',
            mod_description: 'No more insomnia triggers, phantoms are now only rebalanced full moon threats!'
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'    : 'reworkedphantoms',
                'Specification-Vendor'   : 'lightyorugami',
                'Specification-Version'  : '1',
                'Implementation-Title'   : project.name,
                'Implementation-Version' : project.jar.archiveVersion,
                'Implementation-Vendor'  : 'lightyorugami'
        ])
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea.module {
    downloadJavadoc = true
    downloadSources = true
}

eclipse {
    synchronizationTasks 'genEclipseRuns'
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}